GET http://localhost:3000/create
###

POST http://localhost:3000/register
Content-Type: application/json

{
"username":"nagasritha",
"password":"nag#$%",
"email":"nagasritha@2021gmail.com",
"gender":"female",
"location":"Hindupure"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"naganithesh",
    "email":"naganithesh@2021gmail.com",
    "password":"nag#$%123"
}
###

GET http://localhost:3000/galery
###

POST http://localhost:3000/add-image
Content-Type: application/json

{
    "imageUrl":"abcd.jpg"
}

###

GET http://localhost:3000/images